### ISSUE TITLE
New parameter name

### ISSUE THREAD

**Issue by ossinkine** [lookyman/phpstan-symfony#13]
`srcDevDebugProjectContainerXml` is very strange. It does not say at all why it is needed. Moreover parameters is usually named using snake notation.
I suggest to change it to `container_xml_path`.
If you agree or you can suggest better name I will create a PR.

**Comment by lookyman** [comment]
We can rename the parameter, but please stick with camelCase naming, which is a defacto standard in neon.. I like your `containerXmlPath` suggestion.

**Comment by ossinkine** [comment]
Could you please give a link to the specification with camelCase naming?
Here I don't see camel case but see snake case https://ne-on.org/
PHPStan also uses snake notation https://github.com/phpstan/phpstan#configuration
