### ISSUE TITLE
Default container path

### ISSUE THREAD

**Issue by random-name-here** [lookyman/phpstan-symfony#17]
Default path to container should be
container_xml_path: %rootDir%/../../../var/cache/dev/appDevDebugProjectContainer.xml

xml file names appDevDebugProjectContainer.xml, not srcDevDebugProjectContainer.xml.

**Comment by lookyman** [comment]
What version of Symfony are you using?

**Comment by random-name-here** [comment]
Symfony 3.4 SE

**Comment by lookyman** [comment]
Ahh, I believe the name has changed in 4.0.. I could mention something about it in readme.

**Comment by lookyman** [comment]
Fixed by 576cc147bf70bdad9fa1afc7f33528b921a4b171
