### ISSUE TITLE
Right ObjectManager::getRepository function return type

### ISSUE THREAD

**Issue by HEKET313** [lookyman/phpstan-symfony#20]
Default `ObjectManager::getRepository` function return type is `\Doctrine\Common\Persistence\ObjectRepository`
That's right but actually this function are used for returning different repositories. For example if I pass to this function argument `App\Entity\Photo` that means that this function return to me repository of this entity: `App\Repository\PhotoRepository` which is extended from `ObjectRepository` class
Now PHPStan doesn't recognise this type properly, it thinks that this function returns me common ObjectRepository object and of course shows me an error that it can not find my custom methods of my repository class.

**Comment by lookyman** [comment]
You should check out https://github.com/phpstan/phpstan-doctrine/.

**Comment by HEKET313** [comment]
Thanks
