### ISSUE TITLE
Dependency on roave/security-advisories

### ISSUE THREAD

**Issue by Jan0707** [lookyman/phpstan-symfony#6]
While I certainly get the benefit from including that repository, I do not quite understand why it is listed as a dependency and not a dev-dependency. 

Good for this project to make use of secure packages only, but forcing such limitations upon all users who would want to install this extensions seems a bit harsh, doesn't it ?

**Comment by lookyman** [comment]
It is a bit harsh, I agree. But for a good reason. Security of online applications really important, that is why I am enforcing this dependency in this as well as all other packages.

**Comment by lookyman** [comment]
Moreover, it just takes one `composer require roave/security-advisories:dev-master` command and you are done. :)

**Comment by nicwortel** [comment]
@lookyman I would like to reopen this issue. There are other ways to check for insecure dependencies, such as the SensioLabs Security Checker. Enforcing roave/security-advisories keeps me from using this extension right now.

**Comment by mhujer** [comment]
I think that having `roave/security-advisories` in `require` violations the Single Responsibility Principle. It makes this package do two things:

1) allow efficient use of PHPStan with Symfony
2) enforces specific versions of dependencies in a project


(I understand the benefit of having dependencies checked for insecure versions, but it should not be required to use this package).

**Comment by lookyman** [comment]
On second thought, I guess I could live without the package being required.

**Comment by lookyman** [comment]
https://github.com/lookyman/phpstan-symfony/releases/tag/0.1.1
