### ISSUE TITLE
Support for Symfony ~2.8

### ISSUE THREAD

**Issue by Jan0707** [lookyman/phpstan-symfony#8]
Hey there,

I was wondering about the lack of support for symfony ~2.8. Given that it is a LTS version and will be supported until the end of 2019 I feel like there are many users that would appreciate the support (full disclosure: including me).

I see that the package requires the symfony-di component and restricts it to ~3.2|~4.0 

Do you think support for ~2.8 is possible ? Is that something that would be wort looking into or is it more of a hopeless endeavour? 

Kind regards :)

**Comment by lookyman** [comment]
Sure, the only reason for the restriction is that 3.2 was the version I was using when I made this package. If there are no significant differences in 2.8's DI, it should work fine. You can send a pull request if you want, otherwise I'll look into it.

**Comment by lookyman** [comment]
Fixed by 83997c8.
